# This file defines the steps for Google Cloud Build to execute.
steps:
# Step 1: Build the backend Flask image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:latest',
    './Legal_Mcp'  # Directory of the backend Dockerfile
  ]

# Step 2: Push the backend image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:latest'
  ]

# Step 3: Build the frontend Next.js image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/frontend:latest',
    './sahayai'  # Directory of the frontend Dockerfile
  ]

# Step 4: Push the frontend image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/frontend:latest'
  ]

# This final section makes both images available to Cloud Run after the build completes.
images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:latest'
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/frontend:latest'
